version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:your-app-key-here
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
      # Optional: weitere ENV-Variablen wie MAIL_*, CACHE_DRIVER, SESSION_DRIVER
      # Alternativ: env_file: .env
    volumes:
      - ./backend/database:/var/www/database
      - ./backend/storage:/var/www/storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
   