services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY:-base64:ckuyGMELw9XmfgS+dTMLcee7ab9LR8r+dvfxq9zlfCQ=}
      - APP_URL=${APP_URL:-http://localhost:8080}
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - SESSION_DRIVER=database
      - CACHE_DRIVER=database
      - QUEUE_CONNECTION=database
      - SANCTUM_STATEFUL_DOMAINS=${SANCTUM_STATEFUL_DOMAINS:-localhost:3000,localhost:8080}
      - SESSION_DOMAIN=${SESSION_DOMAIN:-localhost}
    volumes:
      - database_data:/var/www/database
      - storage_data:/var/www/storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  database_data:
  storage_data:
   