version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:your-app-key-here
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    volumes:
      - ./backend/database:/var/www/database
      - ./backend/storage:/var/www/storage
    restart: unless-stopped

  # Optional: Add a database service if needed
  # mysql:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: portfolio
  #     MYSQL_USER: portfolio
  #     MYSQL_PASSWORD: portfolio
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   restart: unless-stopped

# volumes:
#   mysql_data: